"""
3D generation routes — OpenSCAD case generation and Meshy task proxy.

POST /api/generate/case          — AI-generate OpenSCAD case from object dims
GET  /api/generate/meshy/{id}    — poll Meshy task status via CF worker
POST /api/generate/openscad      — compile OpenSCAD code → STL
GET  /api/generate/stl/{filename} — download a compiled STL
POST /api/generate/compile-case  — generate case SCAD + compile to STL in one shot
"""
import os
import re
import uuid
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field

from core.logger import get_logger

log = get_logger(__name__)
router = APIRouter()

STL_DIR = Path("scan_data/stls")


# ── Request models ──────────────────────────────────────────────────────────

class GenerateCaseRequest(BaseModel):
    name: str
    width_mm: float = Field(..., ge=0)
    depth_mm: float = Field(..., ge=0)
    height_mm: float = Field(..., ge=0)
    padding_mm: float = Field(2.0, ge=0, le=20)
    wall_mm: float = Field(2.0, ge=1, le=10)


# ── Shared helper (also called from scan route) ─────────────────────────────

async def _generate_case_openscad(
    name: str,
    width_mm: float,
    depth_mm: float,
    height_mm: float,
    padding_mm: float = 2.0,
    wall_mm: float = 2.0,
) -> str:
    """
    Call Gemini to generate parametric OpenSCAD code for a protective box case.
    Falls back to a built-in parametric template when GEMINI_API_KEY is unset.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        log.info("GEMINI_API_KEY not set — returning built-in case template")
        return _builtin_case_template(name, width_mm, depth_mm, height_mm, padding_mm, wall_mm)

    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
        model = genai.GenerativeModel(model_name)

        prompt = f"""Generate parametric OpenSCAD code for a two-part protective box case with friction-fit lid.

Object to house:
  Name: {name}
  Width: {width_mm} mm
  Depth: {depth_mm} mm
  Height: {height_mm} mm
  Padding each side: {padding_mm} mm
  Wall thickness: {wall_mm} mm

Requirements:
- Parametric variables at top for all dimensions
- Box base with interior cavity sized to object + padding
- Friction-fit lid (0.2 mm press-fit tolerance)
- Chamfered outer edges (1 mm) for printability without supports
- Finger notch on one short side of the lid for easy removal
- Both parts printable flat (no supports needed)
- Modules: case_base() and case_lid()
- Call both at the bottom with a gap between them for plate layout

Reply ONLY with the OpenSCAD code. No markdown, no explanation."""

        response = await model.generate_content_async(prompt)
        code = response.text.strip()
        # Strip markdown fences if the model adds them anyway
        if code.startswith("```"):
            lines = code.splitlines()
            code = "\n".join(
                lines[1:-1] if lines[-1].strip() == "```" else lines[1:]
            ).strip()
        return code

    except Exception as e:
        log.error("Gemini case generation failed: %s", e)
        log.info("Falling back to built-in case template")
        return _builtin_case_template(name, width_mm, depth_mm, height_mm, padding_mm, wall_mm)


def _builtin_case_template(
    name: str,
    width_mm: float,
    depth_mm: float,
    height_mm: float,
    padding_mm: float,
    wall_mm: float,
) -> str:
    return f"""// Case for: {name}
// Generated by Holomat

obj_w   = {width_mm};    // object width mm
obj_d   = {depth_mm};    // object depth mm
obj_h   = {height_mm};   // object height mm
pad     = {padding_mm};  // padding each side mm
wall    = {wall_mm};     // wall thickness mm
chf     = 1;             // chamfer mm
tol     = 0.2;           // friction-fit tolerance mm
notch_w = 15;            // finger notch width mm
notch_d = 4;             // finger notch depth mm

inner_w = obj_w + pad * 2;
inner_d = obj_d + pad * 2;
inner_h = obj_h + pad;
outer_w = inner_w + wall * 2;
outer_d = inner_d + wall * 2;
base_h  = inner_h + wall;
lid_h   = wall + 4;      // lid height mm

module chamfer_box(w, d, h, c) {{
  hull() {{
    for (x = [c, w-c]) for (y = [c, d-c]) {{
      translate([x, y, 0]) cylinder(r=c, h=h, $fn=16);
    }}
  }}
}}

module case_base() {{
  difference() {{
    chamfer_box(outer_w, outer_d, base_h, chf);
    translate([wall, wall, wall])
      cube([inner_w, inner_d, inner_h + 1]);
    // Lip recess for lid
    translate([wall - tol/2, wall - tol/2, base_h - 4])
      cube([inner_w + tol, inner_d + tol, 4.1]);
  }}
}}

module case_lid() {{
  difference() {{
    chamfer_box(outer_w, outer_d, lid_h, chf);
    // Inner lip that presses into base
    translate([wall, wall, -0.1])
      cube([inner_w, inner_d, lid_h]);
    // Finger notch
    translate([(outer_w - notch_w) / 2, -0.1, lid_h - notch_d])
      cube([notch_w, notch_d + 0.1, notch_d + 0.1]);
  }}
}}

// Plate layout
case_base();
translate([outer_w + 5, 0, 0])
  case_lid();
"""


# ── Routes ──────────────────────────────────────────────────────────────────

@router.post("/case")
async def generate_case(body: GenerateCaseRequest) -> JSONResponse:
    try:
        code = await _generate_case_openscad(
            name=body.name,
            width_mm=body.width_mm,
            depth_mm=body.depth_mm,
            height_mm=body.height_mm,
            padding_mm=body.padding_mm,
            wall_mm=body.wall_mm,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return JSONResponse({"name": body.name, "code": code})


@router.get("/meshy/{task_id}")
async def meshy_status(task_id: str) -> JSONResponse:
    cf_url = os.getenv("CF_API_URL", "").rstrip("/")
    cf_key = os.getenv("CF_API_KEY", "")
    if not cf_url:
        raise HTTPException(status_code=503, detail="CF_API_URL not configured")

    import httpx
    headers: dict[str, str] = {}
    if cf_key:
        headers["X-API-Key"] = cf_key

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            r = await client.get(f"{cf_url}/api/meshy/status/{task_id}", headers=headers)
        return JSONResponse(r.json(), status_code=r.status_code)
    except httpx.RequestError as e:
        raise HTTPException(status_code=502, detail=f"CF worker unreachable: {e}")


class CompileRequest(BaseModel):
    scad_code: str
    name: str = "model"


def _safe_name(name: str) -> str:
    return re.sub(r"[^a-z0-9_-]", "_", name.lower())[:30]


def _stl_response(filename: str) -> dict:
    path = STL_DIR / filename
    return {
        "filename": filename,
        "size_bytes": path.stat().st_size,
        "download_url": f"/api/generate/stl/{filename}",
    }


@router.post("/openscad")
async def compile_openscad_route(body: CompileRequest) -> JSONResponse:
    """Compile arbitrary OpenSCAD code to a binary STL. Returns a download URL."""
    from core.slicer import compile_openscad, openscad_available

    if not openscad_available():
        raise HTTPException(status_code=503, detail="OpenSCAD is not installed on this server")

    STL_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{_safe_name(body.name)}_{uuid.uuid4().hex[:8]}.stl"
    stl_path = str(STL_DIR / filename)

    try:
        await compile_openscad(body.scad_code, stl_path)
    except RuntimeError as e:
        raise HTTPException(status_code=422, detail=str(e))

    return JSONResponse({"name": body.name, **_stl_response(filename)})


@router.get("/stl/{filename}")
async def download_stl(filename: str) -> FileResponse:
    """Download a previously compiled STL file."""
    if not filename.endswith(".stl") or "/" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")
    stl_path = STL_DIR / filename
    if not stl_path.exists():
        raise HTTPException(status_code=404, detail="STL not found")
    return FileResponse(str(stl_path), media_type="application/octet-stream", filename=filename)


@router.post("/compile-case")
async def compile_case(body: GenerateCaseRequest) -> JSONResponse:
    """Generate an OpenSCAD case from object dimensions and compile it to STL in one shot."""
    from core.slicer import compile_openscad, openscad_available

    if not openscad_available():
        raise HTTPException(status_code=503, detail="OpenSCAD is not installed on this server")

    try:
        code = await _generate_case_openscad(
            name=body.name,
            width_mm=body.width_mm,
            depth_mm=body.depth_mm,
            height_mm=body.height_mm,
            padding_mm=body.padding_mm,
            wall_mm=body.wall_mm,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    STL_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{_safe_name(body.name)}_{uuid.uuid4().hex[:8]}.stl"
    stl_path = str(STL_DIR / filename)

    try:
        await compile_openscad(code, stl_path)
    except RuntimeError as e:
        raise HTTPException(status_code=422, detail=str(e))

    return JSONResponse({"name": body.name, **_stl_response(filename)})
